---
title: "Market Volatility"
author: "Jeff Chandler"
date: "November 13, 2016"
output: html_document
---

#This is Unit 11 Lecture Assignment

###Load the necessary packages and libraries

```{r}

setwd('C:\\Rprojects\\Unit11LectureAssign\\Analysis')
source('PackageInstall.R')
```

###Get the data from the internet
```{r}
##get the data
histquot = get.hist.quote('^gspc', quote = 'Close')
```

###Calculate the return
```{r}

snpreturn = log(lag(histquot)) - log(histquot)

```

###Create the function and create the volatility estimate

```{r}
vol = function(d, logrets){
  var=0
  lam=0
  varlist = c()
  for (r  in logrets) 
  {
    lam = lam*(1 -1/d) + 1
    var = (1-1/lam)*var + (1/lam)*r^2
    varlist = c(varlist, var)
    
  }
  sqrt(varlist)
}
volest = vol(10,snpreturn)
volest1 = vol(30, snpreturn)
volest2 = vol(100, snpreturn)
```

###Build the plot showing the 3 estimates
```{r}
plot(volest*100, ylab='Percet %', type = 'l', col='red')
lines(volest1*100, type = 'l',col='green')
lines(volest2*100, type = 'l', col='blue')
```

